apiVersion: apps/v1
kind: Deployment
metadata:
  name: cc-deployment
  labels:
    app: devapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devapp
  template:
    metadata:
      labels:
        app: devapp
    spec:
      containers:
      - name: nodeserver
        image: amasha97/devapp:latest
        ports:
        - containerPort: 3000