name: Publish Docker Image to Registry and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    name: Push Docker image to Docker Hub
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: amasha97/devapp
      
      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Start minikube
        uses: medyagh/setup-minikube@master
        
      - name: Try the cluster !
        run: |
          minikube start
          kubectl get pods -A
        
      - name: Build image
        run: |
          export SHELL=/bin/bash
          eval $(minikube -p minikube docker-env)
          docker build -f ./Dockerfile -t amasha97/devapp .
          echo -n "verifying images:"
          docker images        
          
      - name: Deploy to minikube
        run: |
          kubectl apply -f deployment.yml
          kubectl apply -f service.yml
          
      - name: Test service URLs
        run: |
          kubectl expose deployment cc-deployment --type=LoadBalancer --port=8080
          minikube service list
          minikube service cc-service --url
          kubectl get ep -o wide
